vich_uploader:
    db_driver: orm

    mappings:
        books_images:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true